config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :dancers

end

app/models/dancer.rb
class Dancer < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dancers_controller.rb
class DancersController < ApplicationController

  def index
    @dancer = Dancer.new
    @dancers = Dancer.all
  end

  def create
    @dancer = Dancer.create(dancer_params)
    if @dancer.save
      redirect_to dancers_path
    else
      render :index
    end
  end

  def show
    @dancer = Dancer.find(params[:id])
  end

  def edit
    @dancer = Dancer.find(params[:id])
  end

  def update
    @dancer = Dancer.find(params[:id])
    @dancer.update_attributes!(dancer_params)

    redirect_to dancers_path
  end

  def destroy
    @dancer = Dancer.find(params[:id]).delete

    redirect_to dancers_path
  end


  private
  def dancer_params
    params.require(:dancer).permit(:name, :genre)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dancers/edit.html.erb
<%= form_for @dancer do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </p>
  <p>
    <%= f.submit 'Update dancer' %>
  </p>
<% end %>

app/views/dancers/index.html.erb
<%= form_for @dancer do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </p>
  <p>
    <%= f.submit 'Create Dancer' %>
  </p>
<% end %>

<% @dancers.each do |dancer| %>
<ul>
  <li>
    <%= dancer.name %>, <%= dancer.genre %>
  </li>
</ul>
<% end %>

app/views/dancers/show.html.erb
<ul>
  <li>
    <%= @dancer.name %>, <%= @dancer.genre %>
  </li>
</ul>

<%= link_to 'Edit dancer', edit_dancer_path(@dancer) %>
<%= link_to 'Delete dancer', dancer_path(@dancer), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudDancers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Welcome</h2>

<%= link_to 'Add a Dancer', dancers_path %>